### ISSUE TITLE
Plugin Clarity

### ISSUE THREAD

**Issue by aljawaid** [greyaz/TableView#1]
Hello, this looks like a useful plugin... kindly keep your screenshots (or the main one at least) in English so we can vision the plugin in our own instances.

My question is, does this plugin add a new section/table view to the project bar or is it replacing the existing 'list' button?

**Comment by greyaz** [comment]
Thank you @aljawaid. 
This is an option in the config file. You can choose to keep the list view or not. 
I will update the readme file with more details.
