### ISSUE TITLE
TableView plugin remanis as ready for installation plugins list after it was installed

### ISSUE THREAD

**Issue by salazarjoelo** [greyaz/TableView#2]
Hi tere. Great job!!!!
Just for your knowledge I open this issue about once installed it still appears in the plugins list for install in kanboard instance.

**Comment by greyaz** [comment]
@salazarjoelo ,
Thank you, I will verify this problem.

**Comment by greyaz** [comment]
@salazarjoelo This issue has been fixed by updating the plugin name on kanboard plugin page.

**Comment by salazarjoelo** [comment]
Thanks @Grey!!
 Yes, I updated it and it is showing correctly in plugins installed ,as appears as an installed plugin in plugins directory.
