### ISSUE TITLE
"nb_metadata" not found

### ISSUE THREAD

**Issue by cahedral** [greyaz/TableView#3]
Warning: Undefined array key "nb_metadata" in /kb/plugins/TableView/Template/project_dashboard/show.php on line 29

Versión de la aplicación: 1.2.32
Versión de PHP: 8.2.4
PHP SAPI: apache2handler
Cliente HTTP: cURL
Versión del sistema operativo: Windows NT 10.0
Driver de la base de datos sqlite
Versión de base de datos: 3.39.2
Navegador: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by saijnawazaki** [comment]
open  /kb/plugins/TableView/Template/project_dashboard/show.php line 29 add "isset($task['nb_metadata'])"

like
`if (isset($task['nb_metadata']) && $task['nb_metadata'] > 0){`

**Comment by cahedral** [comment]
What is that variable used for?

Does not exist in the entire project "kanboard"

**Comment by saijnawazaki** [comment]
Maybe Plugin

**Comment by greyaz** [comment]
I will fix it in the next version.
