### ISSUE TITLE
"owner_ms" not found

### ISSUE THREAD

**Issue by cahedral** [greyaz/TableView#4]
Warning: Undefined array key "owner_ms" in /kb/plugins/TableView/Template/table_view/other_assignees.php on line 1

Versión de la aplicación: 1.2.32
Versión de PHP: 8.2.4
PHP SAPI: apache2handler
Cliente HTTP: cURL
Versión del sistema operativo: Windows NT 10.0
Driver de la base de datos sqlite
Versión de base de datos: 3.39.2
Navegador: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by saijnawazaki** [comment]
u can simply edit file /kb/plugins/TableView/Template/table_view/other_assignees.php line 1 add "isset($task['owner_ms'])"

like with
`<?php if (isset($task['owner_ms']) && $task['owner_ms'] > 0 && count($this->task->multiselectMemberModel->getMembers($task['owner_ms'])) > 0) : ?>`

**Comment by cahedral** [comment]
What is that variable used for?

Does not exist in the entire project "kanboard"

**Comment by saijnawazaki** [comment]
> What is that variable used for?
> 
> Does not exist in the entire project "kanboard"

Maybe for "Group_Assign"
https://github.com/kanboard/kanboard/issues/4691#issuecomment-751908629

**Comment by greyaz** [comment]
I will fix it in the next version.
